const dimensions = {
  tooltipWidth: 474,
  tooltipHeight: 203,
  mainTooltipWidth: 559,
};

const styles = {
  addedTooltip: {
    fontFamily: "Inter",
    position: "fixed",
    top: "0px",
    left: "0px",
    display: "none",
    overflow: "hidden",
    cursor: "text",
    zIndex: 2,
    width: `${dimensions.tooltipWidth}px`,
    height: `${dimensions.tooltipHeight}px`,
    boxSizing: "content-box",
    background: "#FFFFFF",
    border: "1px solid #E7E7E7",
    boxShadow:
      "0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)",
    borderRadius: "8px",
  },
  dataTag: {
    marginTop: "14px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    padding: "4px 8px",
    gap: "8px",
    height: "24px",
    background: "#FFFFFF",
    border: "1px solid #D0D0D0",
    borderRadius: "4px",
  },
  addedSafetypeMainButton: {
    position: "fixed",
    bottom: "53px",
    right: "50px",
    cursor: "pointer",
    width: "48px",
    height: "48px",
    backgroundColor: "rgb(32, 203, 219)",
    borderRadius: "50%",
    userSelect: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow:
      "0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)",
  },
  safetypeShutDown: {
    userSelect: "none",
    height: "calc(100% - 48px)",
    display: "none",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "24px",
    padding: "24px 0px",
  },
  countSafetypeIssues: {
    position: "absolute",
    bottom: "-5px",
    right: "-5px",
    backgroundColor: "#FD853A",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    color: "white",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "12px",
  },
  mainTooltip: {
    fontFamily: "Inter",
    position: "fixed",
    bottom: "130px",
    display: "none",
    overflow: "hidden",
    cursor: "text",
    width: `${dimensions.mainTooltipWidth}px`,
    boxSizing: "content-box",
    background: "#FFFFFF",
    border: "1px solid #E7E7E7",
    boxShadow:
      "0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)",
    borderRadius: "8px",
  },
  overlay: {
    position: "absolute",
    padding: "14px 48px 14px 16px",
    pointerEvents: "none",
    maxHeight: "100%",
    overflowY: "scroll",
    cursor: "text",
    width: "750px",
  },
  dynamicOverlay: {
    cursor: "text",
    visibility: "visible",
    overflowX: "hidden",
  },
  tooltipCurrTitle: {
    userSelect: "initial",
    fontSize: "14px",
    lineHeight: "18px",
    textAlign: "center",
    color: "#121212",
    whiteSpace: "nowrap",
  },
  mainTooltipHeader: {
    backgroundColor: "#f7f7f7",
    height: "48px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 16px",
    borderBottom: "1px solid #E7E7E7",
  },
  wellDoneStatus: {
    userSelect: "none",
    height: "166px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
  },
  currentIssueText: {
    backgroundColor: "#FDDCAB",
    textDecoration: "underline",
    textDecorationColor: "#fb6514",
    color: "black",
    fontSize: "14px",
  },
  shutDownPerm: {
    border: "1px solid #D0D0D0",
    color: "#121212",
    fontSize: "14px",
    borderRadius: "4px",
    padding: "8px 12px",
    cursor: "pointer",
    width: "160px",
    textAlign: "center",
  },
  shutDownSession: {
    background: "#121212",
    color: "white",
    fontSize: "14px",
    borderRadius: "4px",
    padding: "8px 12px",
    cursor: "pointer",
    width: "160px",
    textAlign: "center",
  },
};
